[package]
name = "ldk-tutorial-node"
version = "0.1.0"
authors = ["Valentine Wallace <vwallace@protonmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning = { version = "0.0.99", git = "https://git.bitcoin.ninja/rust-lightning", branch = "2021-07-new-closing-fee" }
lightning-block-sync = { version = "0.0.99", git = "https://git.bitcoin.ninja/rust-lightning", branch = "2021-07-new-closing-fee", features = [ "rpc-client" ] }
lightning-invoice = { version = "0.7", git = "https://git.bitcoin.ninja/rust-lightning", branch = "2021-07-new-closing-fee" }
lightning-net-tokio = { version = "0.0.99", git = "https://git.bitcoin.ninja/rust-lightning", branch = "2021-07-new-closing-fee" }
lightning-persister = { version = "0.0.99", git = "https://git.bitcoin.ninja/rust-lightning", branch = "2021-07-new-closing-fee" }
lightning-background-processor = { version = "0.0.99", git = "https://git.bitcoin.ninja/rust-lightning", branch = "2021-07-new-closing-fee" }

base64 = "0.13.0"
bitcoin = "0.27"
bitcoin-bech32 = "0.12"
bech32 = "0.8"
hex = "0.3"

futures = "0.3"
time = "0.2"
rand = "0.4"
serde_json = { version = "1.0" }
tokio = { version = "1.5", features = [ "io-util", "macros", "rt", "rt-multi-thread", "sync", "net", "time" ] }

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
